services:
  db:
    image: postgres:16
    container_name: lojas_henner_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lojas_henner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lojas_henner_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Corrigir erro exited(1)
  #
  # minio:
  #   image: minio/minio
  #   container_name: lojashenner_minio
  #   ports:
  #     - "9000:9000" # Porta da API do MinIO
  #     - "9001:9001" # Porta do Console Web
  #   environment:
  #     MINIO_ROOT_USER: usuario
  #     MINIO_ROOT_PASSWORD: admin
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio_data:/data

  app:
    build:
      context: . 
      dockerfile: WebAPI/Dockerfile
    container_name: lojashenner_api
    ports:
      - '5015:8080'
    environment:
      - ConnectionStrings__LojasHennerDb=Host=db;Port=5432;Database=lojas_henner_db;Username=postgres;Password=admin
      - Minio__Endpoint=http://host.docker.internal:9000
      - Minio__AccessKey=usuario
      - Minio__SecretKey=admin
      - Minio__BucketName=produtos
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      db:
        condition: service_healthy
      # minio:
      #   condition: service_healthy

volumes:
  postgres_data:
  # minio_data:
