services:
  # Banco de dados
  db:
    image: postgres:16
    container_name: lojas_henner_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lojas_henner_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: